version: '3'

services:
  db:
    image: 'postgres:latest'
    container_name: moviedb
    ports: 
       - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: movies
    volumes:
      - $HOME/docker/data/moviedb:/var/lib/postgresql/data
    networks:
      - app-network
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/app

  back-end:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/movies
    depends_on:
      - db
    volumes:
      - ./backend:/app

networks:
  app-network:
    driver: bridge